/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Brand Palette ──────────────────────────────────────────────
        background:             "#faf5f2",
        surface:                "#faf5f2",
        "surface-bright":       "#faf5f2",
        "surface-lowest":       "#ffffff",
        "surface-container":    "#ece7e4",
        "surface-container-low":"#f5f0ed",
        "surface-container-high":"#e6e2de",
        "surface-container-highest":"#e1dcd8",
        "surface-variant":      "#e1dcd8",
        "surface-dim":          "#d8d4d0",
        "on-surface":           "#302e2d",
        "on-surface-variant":   "#5d5b59",
        "outline":              "#797674",
        "outline-variant":      "#b0acaa",
        // Primary (crimson)
        primary:                "#aa2c32",
        "primary-dim":          "#992027",
        "primary-fixed":        "#ff7574",
        "primary-container":    "#ff7574",
        "primary-fixed-dim":    "#f56364",
        "on-primary":           "#ffefee",
        "on-primary-container": "#4e0009",
        "on-primary-fixed":     "#000000",
        "on-primary-fixed-variant":"#60000d",
        // Secondary (amber/gold)
        secondary:              "#735801",
        "secondary-dim":        "#644c00",
        "secondary-fixed":      "#f9d377",
        "secondary-container":  "#f9d377",
        "secondary-fixed-dim":  "#eac56b",
        "on-secondary":         "#fff1d8",
        "on-secondary-container":"#5f4800",
        "on-secondary-fixed":   "#483500",
        "on-secondary-fixed-variant":"#6a5100",
        // Tertiary (teal)
        tertiary:               "#40606d",
        "tertiary-dim":         "#345461",
        "tertiary-fixed":       "#ccedfe",
        "tertiary-container":   "#ccedfe",
        "tertiary-fixed-dim":   "#bedfef",
        "on-tertiary":          "#e4f5ff",
        "on-tertiary-container":"#3a5967",
        "on-tertiary-fixed":    "#274754",
        "on-tertiary-fixed-variant":"#446371",
        // Error
        error:                  "#b02500",
        "error-dim":            "#b92902",
        "error-container":      "#f95630",
        "on-error":             "#ffefec",
        "on-error-container":   "#520c00",
        // Inverse
        "inverse-surface":      "#0f0e0d",
        "inverse-on-surface":   "#a09c9a",
        "inverse-primary":      "#ff6b6b",
        // Surface tint
        "surface-tint":         "#aa2c32",
      },
      fontFamily: {
        headline: ["Newsreader", "Georgia", "serif"],
        body:     ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        label:    ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        // keep display alias pointing to headline for backward compat
        display:  ["Newsreader", "Georgia", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        "4xl":   "2rem",
        full:    "9999px",
      },
      animation: {
        "fade-in":  "fadeIn 0.7s cubic-bezier(0.22,1,0.36,1) forwards",
        "fade-up":  "fadeUp 0.7s cubic-bezier(0.22,1,0.36,1) forwards",
        "slide-in": "slideIn 0.6s cubic-bezier(0.22,1,0.36,1) forwards",
        float:      "float 8s ease-in-out infinite",
        glow:       "glow 4s ease-in-out infinite alternate",
      },
      keyframes: {
        fadeIn:  { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        fadeUp:  { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        slideIn: { "0%": { opacity: "0", transform: "translateX(-10px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        float:   { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-8px)" } },
        glow:    { "0%": { opacity: "0.3" }, "100%": { opacity: "0.6" } },
      },
    },
  },
  plugins: [],
};
